defaults:
  - _base

sweeps:
  n_rep: 10
  n_obs: [50, 100, 200, 500, 1000]
  n_feats: [2, 4, 8, 16, 32]
  epsilon: [0.2, 0.3, 0.5, 1, 2, 5]

methods_args:
  task_name: logReg
  method_names: ["Chaudhuri_sklearn"]
  # method_names: ["Chaudhuri", "Chaudhuri_sklearn", "BetaBayes", "Minami"]

seed: 0

data:
  group: simulated

wandb_args:
  mode: online
  project: beta-sim-1205

logging:
  plot_args:
    x: "n"
    col: "epsilon"
    row: "loss"
    hue: "method"
    style: "n_feats"
